version: 2.1
orbs:
  slack: circleci/slack@4.12.6

executors:
  ubuntu-22-04:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true

aliases:
  - &print_bucket
    working_directory: /app
    docker:
      - image: sangukou/react-app:latest

jobs:
  prepare:
    docker:
      - image: cimg/base:2022.03

    steps:
      - run: echo "hello from github"

  start-react-app:
    <<: *print_bucket
    steps:
      - run:
          name: start server
          command: |
            npm start &
            cd AutomationUI && npx cypress run

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: C06GH4Z8ACT
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*hello habibi*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

workflows:
  uat:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - uat
      - start-react-app:
          requires:
            - prepare
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - uat
      - notify:
          context: slackNotif
          requires:
            - start-react-app
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - uat
