version: 2.1

jobs:
  print-a-message:
    docker:
      - image: cimg/base:2022.03
    parameters:
      message:
        type: string
    steps:
      - run: echo "<< parameters.message >>"

workflows:
 uat:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - uat
      - print-a-message:
          message: Hello!