version: 2.1

jobs:
  prepare:
    docker:
      - image: cimg/base:2022.03

    steps:
      - run: echo "hello form github"

workflows:
  uat:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - uat