version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  prepare:
    docker:
      - image: cimg/base:2022.03

    steps:
      - run: echo "hello form github"

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: C06GH4Z8ACT
          event: pass
          template: success_tagged_deploy_1

workflows:
  uat:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - uat
      - notify:
          context: slackNotif
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - uat

#add commenthjh ff