name: "Get & Cache Dependencies"
description: "Get the Dependencies (Via npm) and cache them"
inputs:
  caching:
    description: "Wether to cache dependencies or not."
    required: false
    default: 'false' #use cache when false
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash